checkapk(1)

# NAME

*checkapk* - find ABI breakages in package upgrades

# SYNOPSIS

*checkapk* [-h|--help]

# DESCRIPTION

*checkapk* prints ABI changes in package upgrades and prints differences in
metadata in contained files.

# OPTIONS

*-h, --help*
	Print help information and exit.

# FILES

APKBUILD
	Package file on which to operate.

# SEE ALSO

abump(1), abuild(1), APKBUILD(5), apk(8).

# AUTHORS

Natanael Copa <_ncopa@alpinelinux.org_> and open source contributors.
