export CFLAGS="-Os -fstack-clash-protection -Wformat -Werror=format-security"
export CXXFLAGS="-Os -fstack-clash-protection -Wformat -Werror=format-security"
export CXXFLAGS="$CXXFLAGS -D_GLIBCXX_ASSERTIONS=1 -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS=1 -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_FAST"
export LDFLAGS="-Wl,--as-needed,-O1,--sort-common"
export GOFLAGS="-buildmode=pie -modcacherw -trimpath -buildvcs=false"
# Do note that these should work with at least GDC and LDC
export DFLAGS="-Os"

export JOBS="${JOBS:-$(nproc)}"
export MAKEFLAGS="-j$JOBS"
export SAMUFLAGS="-j$JOBS"
export CARGO_BUILD_JOBS="$JOBS"
export CMAKE_BUILD_PARALLEL_LEVEL="$JOBS"
export CTEST_PARALLEL_LEVEL="$JOBS"

export CMAKE_GENERATOR=Ninja

export CARGO_PROFILE_RELEASE_OPT_LEVEL="s"
export CARGO_PROFILE_RELEASE_PANIC="abort"
export CARGO_PROFILE_RELEASE_CODEGEN_UNITS=1
export CARGO_PROFILE_RELEASE_LTO="true"

# Tell the libc crate that our baseline is a time64-enabled musl so that its
# bindings also use the 64-bit time types on 32-bit targets
export RUST_LIBC_UNSTABLE_MUSL_V1_2_3=1

export CTEST_OUTPUT_ON_FAILURE=ON
export CTEST_NO_TESTS_ACTION=error

export PERL_MM_USE_DEFAULT=1

if ! [ -d "${XDG_CACHE_HOME:-$HOME/.cache}/abuild" ] && [ -w /var/cache/distfiles ]; then
	SRCDEST=/var/cache/distfiles
else
	SRCDEST=${XDG_CACHE_HOME:-$HOME/.cache}/abuild
fi

# The package will be stored as $REPODEST/$repo/$arch/$pkgname-$pkgver-r$pkgrel.apk
# where $repo is the name of the parent directory of $startdir.
if ! [ -d "${XDG_DATA_HOME:-$HOME/.local/share}/abuild" ] && [ -d "$HOME/packages" ]; then
	REPODEST=$HOME/packages
else
	REPODEST=${XDG_DATA_HOME:-$HOME/.local/share}/abuild
fi

# what to clean up after a successful build
CLEANUP="srcdir bldroot pkgdir tmpdir deps"

# what to cleanup after a failed build
ERROR_CLEANUP="bldroot deps"
