#!/usr/bin/env atf-sh

. $(atf_get_srcdir)/test_env.sh
init_tests \
	abuild_tar_help \
	abuild_tar_invalid_opt

DATADIR=$(atf_get_srcdir)/testdata

abuild_tar_help_body() {
	atf_check -s exit:0 \
		-o match:"usage:" \
		abuild-tar --help
}

abuild_tar_invalid_opt_body() {
	atf_check -s not-exit:0 \
		-e match:"usage:" \
		abuild-tar --invalid
}
