#!/usr/bin/env atf-sh

. $(atf_get_srcdir)/test_env.sh
init_tests \
	apkgrel_usage

export ABUILD_SHAREDIR=$(atf_get_srcdir)/..

apkgrel_usage_body() {
	atf_check -o match:"usage" apkgrel -h
	atf_check -s exit:2 -e match:"usage" apkgrel -Z
}

