#!/usr/bin/env atf-sh

. $(atf_get_srcdir)/test_env.sh
init_tests \
	checkapk_help \
	checkapk_invalid_opt

DATADIR=$(atf_get_srcdir)/testdata

checkapk_help_body() {
	atf_check -s exit:0 \
		-o match:"Usage:" \
		checkapk --help
}

checkapk_invalid_opt_body() {
	atf_check -s not-exit:0 \
		-e match:"Usage:" \
		checkapk --invalid
}
